/*
 * MATERNAL CONTEXT MODULE (v15, NEXT_STEPS_v14-v17.md Part B) -- PPD-Adapt
 *
 * What this is: a fixed-order, rule-based block of questions about background, history and circumstances
 * (Blocks A, B, C, E, F, G of the roadmap; Block D does not exist in the source plan; Block H and Block S are
 * v16, not built here). It runs AFTER the safety block and BEFORE the adaptive engine (see B.5's session order).
 *
 * What this is NOT: it never changes the Aggregate PPD Score. Per NEXT_STEPS_v14-v17.md Part A.1, risk factors
 * are not symptoms and no accurate tool exists for turning them into a probability of PPD (USPSTF 2019). This
 * module only (a) ROUTES the session (M0: skips the postpartum bonding module if pregnant; labels results
 * "outside the usual postpartum window" if >12 months), (b) DISPLAYS context next to the results (M1: a
 * "Background and context" card, grouped by evidence tier, with a USPSTF increased-risk flag and pathway
 * flags), and (c) changes HOW HARD the adaptive engine looks for Depression/Anxiety before stopping, and the
 * PBQ expansion threshold (M2, behind CONTEXT_RISK_STOPPING.enabled in index.html) -- never the likelihood or
 * the prior, only how many items are asked before the engine is willing to stop. See
 * selection-engine/scripts/context_module.py (the reference implementation this file is read by).
 *
 * Status: item wording, tier assignments and the M2 trigger set are provisional design choices per the
 * roadmap's own evidence tiers (B.2). A clinician must review and sign them (set "status" to e.g.
 * "SIGNED 2026-XX-XX by <name>"). The deploy gate blocks while the marker below is present.
 *
 * Item schema: id, block, type ("single" | "multi"), question, options (array of strings), tier (1|2|3|null),
 * role ("risk" [default when tier set] | "routing" | "pathway" | "care_context"), risk_options (option indices
 * counted as "factor present", single-select), risk_if_any_except (option index treated as "none selected",
 * multi-select -- any OTHER option checked counts as "factor present"), protective_options (option indices
 * counted as protective), m2_trigger (true only for the Tier-1 upfront-history items B.7 names), uspstf_label
 * (set when a "yes"/risk answer should be named in the M1 USPSTF increased-risk line), evidence (citation),
 * held_sample_field (B.6's replication-table mapping, documentation only), skip_if ({item, in: [...]} -- this
 * item is skipped when the named earlier item's answer is one of the listed option strings), points (OSSS-3
 * items only: option index -> scale point, summed with osss3.items for the published band).
 *
 * The object below is plain JSON on purpose (double-quoted keys, no trailing comma) -- so
 * selection-engine/scripts/context_module.py can read it from this file by regex + json.loads, the same
 * "single source of truth" pattern postpartum_module.js and severity_bands.js already use.
 */
const CONTEXT_MODULE = {
 "status": "UNSIGNED - DO NOT DEPLOY",
 "note": "Background and history questions. Never added to the Aggregate PPD Score (NEXT_STEPS_v14-v17.md Part A.1). Changes routing (M0), what is shown alongside the results (M1), and -- only when CONTEXT_RISK_STOPPING.enabled and a Tier-1 history item is positive -- how many Depression/Anxiety items and PBQ items are asked before the engine is willing to stop (M2).",
 "osss3": {"items": ["C4", "C5", "C6"], "poor_max": 8, "moderate_max": 11, "strong_min": 12,
           "note": "Oslo Social Support Scale (OSSS-3), Kocalevent et al. 2018. Published source; wording not independently checked against the original instrument in this session -- verify before deployment."},
 "core_item_ids": ["A1", "A2", "A3", "A4", "B1", "B2", "B3", "B6", "C1", "C2", "C4", "C5", "C6", "E2", "F1", "G1", "G2", "G3"],
 "core_item_ids_note": "SHIPPED DEFAULT as of 2026-09-27 (CONTEXT_MODULE_CORE_ONLY.enabled = true in index.html): the ~16-item core-set alternative from NEXT_STEPS_v14-v17.md Part B.3, PLUS G1-G3 (thyroid/anaemia/substance-use pathway flags) per the project lead's decision -- G1-G3 are medical differentials, not risk-factor burden, and cheap at 3 items, so they ship even though they are not part of Part B.3's original core list. Restricted to the 15 of Part B.3's ~16 items that exist in the module actually built (Block S/S0-S3, privacy-gated IPV items, is v16 and does not exist yet -- if it ships, S0-S3 join this list) plus G1-G3. The FULL Block A-G set (context_module.js's own full item list) is KEPT IN CODE, not deleted, as a config option (`core_only=False` / `CONTEXT_MODULE_CORE_ONLY.enabled=false`) for research/manuscript comparison -- it is simply not what ships to a respondent by default any more.",
 "items": [
  {"id": "A1", "block": "A", "type": "single", "role": "routing",
   "question": "Are you currently pregnant, or have you had a baby?",
   "options": ["Pregnant", "Had a baby in the last 12 months", "Had a baby more than 12 months ago", "Neither"],
   "evidence": "DSM-5 peripartum onset = pregnancy or <=4 weeks after delivery; ICD-11 <=6 weeks; clinical guidelines and research use <=12 months [Riseup-PPD 2024; ACOG CPG 4]",
   "held_sample_field": "newborn age"},
  {"id": "A2", "block": "A", "type": "single", "role": "routing",
   "question": "How long ago did you have your baby?",
   "options": ["Less than 6 weeks ago", "6 to 12 weeks ago", "3 to 6 months ago", "7 to 12 months ago"],
   "skip_if": {"item": "A1", "in": ["Pregnant", "Had a baby more than 12 months ago", "Neither"]},
   "evidence": "Frames onset; personalises module wording (\"your 3-month-old\")",
   "held_sample_field": "newborn age"},
  {"id": "A3", "block": "A", "type": "single", "tier": 2, "risk_options": [0],
   "question": "Is this your first baby?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "Primiparity RR 1.76, class II [Kim 2022]",
   "held_sample_field": "number of children"},
  {"id": "A4", "block": "A", "type": "single", "tier": 2, "risk_options": [0], "uspstf_label": "adolescent parenthood",
   "question": "Which age group are you in?",
   "options": ["Under 20", "20 to 24", "25 to 29", "30 to 34", "35 to 39", "40 or older", "Prefer not to say"],
   "evidence": "Younger age OR 2.1-5.4 [Fisher 2012]; adolescent parenthood is a USPSTF (2019) increased-risk criterion",
   "held_sample_field": "age"},
  {"id": "B1", "block": "B", "type": "single", "tier": 1, "risk_options": [0], "m2_trigger": true, "uspstf_label": "history of depression",
   "question": "Before this pregnancy, were you ever diagnosed with or treated for depression or anxiety?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "History of depression OR 3.09 [Liu 2021; Xu 2026]. A USPSTF (2019) increased-risk criterion",
   "held_sample_field": "PHQ-2 before pregnancy (proxy)"},
  {"id": "B2", "block": "B", "type": "single", "tier": 1, "risk_options": [0], "m2_trigger": true, "uspstf_label": "depression or anxiety during this pregnancy",
   "question": "During this pregnancy, was there a period of 2 weeks or more when you felt down, hopeless or very anxious most days?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "Antenatal depression OR 4.58-7.70; antenatal anxiety OR 2.64-7.07 [Ayadiuno 2026]; antenatal anxiety OR 2.49, \"convincing\" [Kim 2022]",
   "held_sample_field": "PHQ-2 during pregnancy (proxy)"},
  {"id": "B3", "block": "B", "type": "single", "tier": 1, "risk_options": [0], "m2_trigger": true, "uspstf_label": "previous postpartum depression",
   "question": "After a previous birth, did you have depression?",
   "options": ["Yes", "No", "Prefer not to say"],
   "skip_if": {"item": "A3", "in": ["Yes", "Prefer not to say"]},
   "evidence": "Previous PPD is among the strongest predictors [Hutchens 2020; Desta 2020]",
   "held_sample_field": null},
  {"id": "B4", "block": "B", "type": "single", "tier": 2, "risk_options": [0],
   "question": "Before pregnancy, did your mood change before your period strongly enough to affect your daily life?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "PMS OR 2.20, \"highly suggestive\", the strongest single association in Gastaldon 2022 -- the self-reportable proxy for hormonal sensitivity",
   "held_sample_field": null},
  {"id": "B5", "block": "B", "type": "single", "tier": 2, "risk_options": [0],
   "question": "Has a close family member (parent, brother or sister) had depression or another mental illness?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "OR 2.08, GRADE moderate [Kjeldsen 2022]",
   "held_sample_field": null},
  {"id": "B6", "block": "B", "type": "single", "role": "pathway", "risk_options": [0],
   "question": "Have you ever been diagnosed with bipolar disorder, or had several days of feeling unusually high or energetic with little need for sleep?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "ACOG CPG 4 covers bipolar disorder and postpartum psychosis; screening before pharmacotherapy is standard practice. Not verified against the full (paywalled) CPG 4 text.",
   "held_sample_field": null},
  {"id": "B7", "block": "B", "type": "single", "role": "care_context", "risk_options": [0],
   "question": "Are you currently receiving care for your emotional wellbeing (doctor, counsellor, medicine, support group)?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "Care context, not a risk factor -- tells a clinician what has helped before",
   "held_sample_field": null},
  {"id": "C1", "block": "C", "type": "single", "tier": 2, "risk_options": [1], "uspstf_label": "single parenthood",
   "question": "Are you married or living with a partner?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "Unmarried OR 3.4-5.8 [Fisher 2012]. A USPSTF (2019) increased-risk criterion",
   "held_sample_field": "marital status"},
  {"id": "C2", "block": "C", "type": "single", "tier": 1, "risk_options": [2], "protective_options": [0],
   "question": "Can you count on your husband or partner for emotional and practical support?",
   "options": ["Yes, fully", "Somewhat", "No, not really", "Prefer not to say"],
   "skip_if": {"item": "C1", "in": ["No", "Prefer not to say"]},
   "evidence": "Lack of partner empathy/support OR 2.0-9.4 [Fisher 2012]; poor marital relationship OR 3.47-3.56 [Ayadiuno 2026]",
   "held_sample_field": "relationship with husband"},
  {"id": "C3", "block": "C", "type": "single", "tier": 2, "risk_options": [2],
   "question": "How would you describe your relationship with your in-laws, or the family you live with?",
   "options": ["Warm and supportive", "Mixed, some difficulty", "Difficult or hostile", "I don't live with extended family", "Prefer not to say"],
   "evidence": "Hostile in-laws OR 2.1-4.4 [Fisher 2012]; LMIC-specific, directly relevant to the Pakistani/Bangladeshi target population",
   "held_sample_field": "relationship with in-laws; family type"},
  {"id": "C4", "block": "C", "type": "single", "tier": 1,
   "question": "How many people are you close enough to that you can count on them if you have serious personal problems?",
   "options": ["None", "1 or 2", "3 to 5", "6 or more"], "points": [1, 2, 3, 4],
   "evidence": "OSSS-3 item 1. Poor social support RR 3.57 [Xu 2026]",
   "held_sample_field": "support received / needed"},
  {"id": "C5", "block": "C", "type": "single", "tier": 1,
   "question": "How much concern do people show in what you are doing?",
   "options": ["None or little", "Some", "Uncertain", "A lot"], "points": [1, 2, 3, 4],
   "evidence": "OSSS-3 item 2",
   "held_sample_field": "support received / needed"},
  {"id": "C6", "block": "C", "type": "single", "tier": 1,
   "question": "If you needed help, how easy would it be to get practical help from neighbours?",
   "options": ["Very difficult", "Difficult", "Possible", "Easy", "Very easy"], "points": [1, 2, 3, 4, 5],
   "evidence": "OSSS-3 item 3",
   "held_sample_field": "support received / needed"},
  {"id": "E1", "block": "E", "type": "multi", "tier": 2, "risk_if_any_except": 6, "uspstf_label": "significant negative life events",
   "question": "In the last 12 months, have any of these happened to you?",
   "options": ["Death of someone close to you", "Serious illness (yours or a family member's)", "Job loss, yours or your partner's", "Moving house", "Separation from a partner", "A money crisis", "None of these"],
   "evidence": "Life stress was among the most common factors [Hutchens 2020]. \"Significant negative life events\" is a USPSTF (2019) increased-risk criterion",
   "held_sample_field": "major losses"},
  {"id": "E2", "block": "E", "type": "single", "tier": 2, "risk_options": [3, 4], "uspstf_label": "low income / financial strain",
   "question": "How easy is it for your household to cover basic needs such as food, rent and medicine?",
   "options": ["Very easy", "Easy", "Manageable", "Hard", "Very hard", "Prefer not to say"],
   "evidence": "Socioeconomic disadvantage OR 2.1-13.2 [Fisher 2012]. Low income is a USPSTF (2019) increased-risk criterion. Currency-free by design",
   "held_sample_field": "income (for local check)"},
  {"id": "F1", "block": "F", "type": "single", "tier": 2, "risk_options": [2],
   "question": "Was this pregnancy planned or wanted at the time?",
   "options": ["Yes, planned and wanted", "Mixed feelings", "No, not planned or not wanted", "Prefer not to say"],
   "evidence": "Unintended pregnancy OR 1.53, \"highly suggestive\" [Gastaldon 2022; Kim 2022]",
   "held_sample_field": "pregnancy plan"},
  {"id": "F2", "block": "F", "type": "single", "tier": 3, "risk_options": [0],
   "question": "Have you ever had a miscarriage, stillbirth, or the loss of a baby?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "Listed in the attached demographics document; evidence inconsistent, no strong umbrella rating found",
   "held_sample_field": "pregnancy loss"},
  {"id": "F3", "block": "F", "type": "single", "tier": 3, "risk_options": [0],
   "question": "Was your baby born early (before 37 weeks), or did your baby need special or intensive care?",
   "options": ["Yes", "No", "Prefer not to say"],
   "skip_if": {"item": "A1", "in": ["Pregnant"]},
   "evidence": "Preterm OR 2.12, weak, low GRADE [Gastaldon 2022]; preterm/LBW OR 1.79-1.97 [Ayadiuno 2026]",
   "held_sample_field": "pregnancy length; newborn illness"},
  {"id": "F4", "block": "F", "type": "single", "tier": 3, "risk_options": [2],
   "question": "How was your baby born?",
   "options": ["Vaginal birth", "Planned caesarean", "Emergency caesarean", "Prefer not to say"],
   "skip_if": {"item": "A1", "in": ["Pregnant"]},
   "evidence": "Caesarean OR 1.29, \"suggestive\", low GRADE [Gastaldon 2022]",
   "held_sample_field": "mode of delivery"},
  {"id": "F5", "block": "F", "type": "single", "tier": 3, "risk_options": [0],
   "question": "Did you have diabetes or high blood pressure in this pregnancy?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "Gestational diabetes OR 1.60 [Gastaldon 2022]",
   "held_sample_field": "pregnancy diseases"},
  {"id": "F6", "block": "F", "type": "single", "tier": 3, "risk_options": [0],
   "question": "Is your baby's health a worry, or does your baby have a medical condition?",
   "options": ["Yes", "No", "Prefer not to say"],
   "skip_if": {"item": "A1", "in": ["Pregnant"]},
   "evidence": "Infant health problems and NICU are listed in the attached demographics document; evidence mostly narrative",
   "held_sample_field": "newborn illness"},
  {"id": "F7", "block": "F", "type": "single", "tier": 2, "risk_options": [0],
   "question": "Has there been pressure or disappointment in the family about the baby being a boy or a girl?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "Asked about PRESSURE, not the baby's sex, because the direction varies by setting: a 2026 Karachi study found male infants associated with HIGHER PPD (aPR 1.47), opposite an earlier meta-analysis's female-infant finding (OR 1.62) [Liu 2021; Karachi 2026]",
   "held_sample_field": "newborn gender (local check)"},
  {"id": "G1", "block": "G", "type": "single", "role": "pathway", "risk_options": [0],
   "question": "Since the birth, have you been told you have a thyroid problem, or had your thyroid checked and it was abnormal?",
   "options": ["Yes", "No", "Prefer not to say"],
   "skip_if": {"item": "A1", "in": ["Pregnant"]},
   "evidence": "Postpartum thyroiditis mimics depression (DSM-5 criterion C, medical cause). As a risk factor it is \"controversial\" [Zhao 2020], so it is a pathway flag, not a risk point",
   "held_sample_field": null},
  {"id": "G2", "block": "G", "type": "single", "role": "pathway", "risk_options": [0],
   "question": "Have you been told you are anaemic (low iron) in pregnancy or since the birth?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "Anaemia OR 1.47 / 1.75, weak [Gastaldon 2022]. Also directly confounds the Fatigue domain",
   "held_sample_field": null},
  {"id": "G3", "block": "G", "type": "single", "role": "pathway", "risk_options": [0],
   "question": "During pregnancy, did you smoke, or use alcohol or drugs?",
   "options": ["Yes", "No", "Prefer not to say"],
   "evidence": "Smoking in pregnancy OR 2.39, class II [Kim 2022]. Substance use is a DSM-5 criterion-C differential",
   "held_sample_field": null}
 ]
};
